### ISSUE TITLE
How to train a text-conditioned ldm for MNIST dataset?

### ISSUE THREAD

**Issue by nusratdeeptee** [explainingai-code/StableDiffusion-PyTorch#19]
I have a text data for MNIST dataset (1 line text description for each image). I tried to train a text-conditional ldm, using MNIST class conditioned config file (mnist_class_cond.yaml) and setting the condition config for text in this file. However, the trained model is not responding to text input, and it generates random images with different configurations even when the text is asking for a specific requirement (For example, the model is generating images of random numbers even when the text asks to generate images of 3). How to modify the entire setup so that it works for text-condition on MNIST dataset?

**Comment by explainingai-code** [comment]
Hi,

For getting text condition to work for mnist, you would have to do the following steps:
1. Update config for mnist to have the text conditioning related parameters.
	For this you can copy whatever is there in CelebHq[ text conditioning config](https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/main/config/celebhq_text_cond.yaml#L24-L30)
2. Modify mnist dataset to additionally load the text captions while fetching the images. You can look at how its done in [celeb dataset](https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/main/dataset/celeb_dataset.py#L74-L80) and do the same for mnist [here](https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/main/dataset/mnist_dataset.py#L64)
3. In mnist datasets get_item method add the text caption. Similar to how [celeb dataset](https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/main/dataset/celeb_dataset.py#L116-L117) does it 
4. Then for ```training use tools/train_ddpm_cond.py``` and for inference use ```tools/sample_ddpm_cond``` passing in the text prompt here - https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/main/tools/sample_ddpm_text_cond.py#L33  

Can you please confirm if after all of this also the model wasn't able to generate according to the text condition.

**Comment by nusratdeeptee** [comment]
Hi,
I have done all the steps you have mentioned. Still, the model is not working. I even changed the value for down channel and mid channel in the configuration file, nothing works. Here is attached the result for two texts: 'Digit 3 with a small area, long length, very thin, right aligned, narrow and high height.', and 'Digit 0 with a large area, long length, thin, right aligned, wide and high height.' The first row of the image shows images for the first text, repeated for five times. The second row of the image represents the second text in the similar way. 
![x](https://github.com/user-attachments/assets/14ee6a52-b1a0-474b-92ef-b4032387ee9a)

**Comment by nusratdeeptee** [comment]
I have a vocabulary for MNIST dataset which aligned each text with each image perfectly, so my training data is accurate. Here is an example of training data with the text: 'Digit 1 with a very small area, short length, very thin, extremely right aligned, narrow and high height.'
![3](https://github.com/user-attachments/assets/69778bd8-ba35-48bf-aa66-771f028ae2f2)

**Comment by explainingai-code** [comment]
@nusratdeeptee 
In order to see if there are any issues with the code, I trained on a toy text dataset for mnist, where the captions were just "generate image of <number>".
And the model ended up generating decent results based on text after 5-6 epochs only. While this is a very simple dataset but atleast the model and code should end up honoring the text condition you are training on.
Here are some sample generation outputs.
'generate image of 6'  -> <img src="https://github.com/user-attachments/assets/b4ab75ee-26f0-4369-bb3e-bdc5cd011874" width="30">
'generate image of 3' ->  <img src="https://github.com/user-attachments/assets/90a71420-dc71-4bff-ab02-3cd08316e71b" width="30">
'generate image of 0' ->  <img src="https://github.com/user-attachments/assets/fa97a1c3-ccaf-4129-8a3b-2cc5f7bf09b2" width="30">

For how many iterations did you train on your dataset ? Maybe you need to train it more. Also, did you try generating output with classifier guidance (if not can you try with a guidance scale of 5 and see if the results are any better)?

**Comment by nusratdeeptee** [comment]
Hi,
Thank you for sharing your results, it helped me identify the problem. While I tried to reproduced your experiment, I realized that my model was not receiving the text data in the right format. I fixed the issue and now it is working great!! Thank you for your help.
