### ISSUE TITLE
Potential double scaling of `lpips_loss` in `tools\train_vqvae.py`

### ISSUE THREAD

**Issue by Malengu** [explainingai-code/StableDiffusion-PyTorch#34]
Hi, thank you for creating such great content! I’ve been following your diffusion series on YouTube, and it’s been incredibly insightful. While exploring your Stable Diffusion GitHub repository, I noticed something in `tools/train_vqvae.py` that I wanted to bring to your attention. It seems the `lpips_loss` might be scaled twice by `acc_steps`, which could affect the calculation. I’m not sure if this is intentional or if I might have misunderstood something. Thank you for all your hard work, and I really appreciate your contributions!

**Comment by explainingai-code** [comment]
Thank you @Malengu for your kind words 
Yes you are absolutely right, I incorrectly scaled by 1/acc_steps in two places [here](https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/main/tools/train_vqvae.py#L141-L143) .
Infact because the same code was also copy pasted for some of other repos, this error ended up in those as well. Have fixed it for SD repo with [this](https://github.com/explainingai-code/StableDiffusion-PyTorch/commit/f562b158a424d0d88474829a4e3200d4cebb58aa) commit and also have fixed it in other repos.
Thank you so much for bringing this to my attention.
