### ISSUE TITLE
Question about sampling data

### ISSUE THREAD

**Issue by jpmcarvalho** [explainingai-code/StableDiffusion-PyTorch#7]
Hello,
First of all thanks again for sharing the code and good work on that!

I have one doubt about sampling data (after training fase).

When "t" is not equal to zero you are using x0 into "im" variable (instead using mean + sigma * z) but when t is equal to zero you are using the mean variable. Why?

I guess you should use always mean + sigma * z every time when t is not equal to zero right?

**Comment by explainingai-code** [comment]
Hello,

Yes but that is just for the saving images part. The reason its like that cause for conditional cases I wanted to get original image prediction at all time to visualize when does diffusion start getting a good original image prediction(and I also needed it for my videos to compare how quickly model reaches a good original image predictions with/without conditioning ). Thats why instead of saving xt at all time instances, I save x0_pred for all cases except t=0.

If you look at unconditional sampling, there I am saving xt only (https://github.com/explainingai-code/StableDiffusion-PyTorch/blob/main/tools/sample_ddpm_vqvae.py#L42). So it was just a matter of what I wanted to save and after that forgot to modify. But you are right, will change to consistently save xt all places.

**Comment by jpmcarvalho** [comment]
Thank you very much!
